modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "neruina_test"
version = "${version}"
displayName = "Neruina Test"
authors = "Bawnorton"
description = '''
This is a mod that tests the functionality of Neruina.
'''

[[mixins]]
config = "neruina_test-common.mixins.json"

[[mixins]]
config = "neruina_test.mixins.json"

[[dependencies.neruina_test]]
modId = "neoforge"
type = "required"
versionRange = "[20.4.46-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.neruina_test]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"