org.gradle.jvmargs=-Xmx4G
loom.ignoreDependencyLoomVersionValidation=true

fabric_versions=1.19.2, 1.19.4, 1.20.1, 1.20.6, 1.21, 1.21.3, 1.21.5
neoforge_versions=1.20.6, 1.21, 1.21.3, 1.21.5

mod_version=2.3.0-beta.4
mod_group=com.bawnorton
mod_id=neruina
mod_name=Neruina
mod_description=This is a mod that prevents ticking entity and ticking block entity / tile entity crashes from bricking worlds.

modrinth_project_id=1s5x833P
curseforge_project_id=851046

fabric_loader=0.15.11

mixin_extras=0.3.5
httpcore5=5.3.1
kohsuke_github=1.318
jackson=2.17.0
maven_artifact=3.8.1