org.gradle.jvmargs=-Xmx4G
loom.ignoreDependencyLoomVersionValidation=true

mod.version=3.0.0
mod.group=com.bawnorton
mod.id=neruina
mod.name=Neruina
mod.author=Bawnorton
mod.license=MIT
mod.description=This is a mod that prevents ticking entity and ticking block entity / tile entity crashes from bricking worlds.

publishing.modrinth=1s5x833P
publishing.curseforge=851046

fabric_loader=0.16.14

httpcore5=5.3.1
kohsuke_github=1.318
jackson=2.17.0
maven_artifact=3.8.1