org.gradle.jvmargs=-Xmx4G
loom.ignoreDependencyLoomVersionValidation=true

mod.version=3.2.2
mod.group=com.bawnorton
mod.id=neruina
mod.name=Neruina
mod.author=Bawnorton
mod.license=MIT
mod.description=This is a mod that prevents ticking entity and ticking block entity / tile entity crashes from bricking worlds.

publishing.modrinth=1s5x833P
publishing.curseforge=851046

fabric_loader=0.18.2