modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Bawnorton/Neruina/issues"
license = "MIT"

[[mods]]
modId = "neruina"
version = "${version}"
displayName = "Neruina"
authors = "Bawnorton"
description = '''
This is a mod that prevents ticking entity and ticking block entity / tile entity crashes from bricking worlds.
'''
logoFile = "icon.png"

[[mixins]]
config = "neruina-common.mixins.json"

[[mixins]]
config = "neruina.mixins.json"

[[dependencies.neruina]]
modId = "neoforge"
type = "required"
versionRange = "[20.4.46-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.neruina]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"