modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "neruina_test"
version = "${version}"
displayName = "Neruina Test"
authors = "Bawnorton"
description = '''
This is a mod that tests the functionality of Neruina.
'''
#logoFile = ""

[[dependencies.neruina_test]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.neruina_test]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.neruina_test]]
modId = "neruina"
mandatory = true
versionRange = "[1.0,)"
ordering = "AFTER"
side = "BOTH"